spring:
  application:
    name: task
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:memory:myDb?cache=shared
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
api:
  security:
    token:
      secret: ${SECRET}
server:
  port: 8080

logging:
  file:
    name: logs/app.log
    path: logs
    max-size: 10MB
  level:
    root: DEBUG
    org.springframework.web: INFO
    br.janioofi.task: INFO